### ISSUE TITLE
Usage in library mode in gulp throws error: Cannot find module 'octopus-deploy'

### ISSUE THREAD

**Issue by dgurram** [parkerholladay/node-octopus-deploy#2]
I've installed v1.0.1 of this package in my project locally and am using it within a gulp task. When I run gulp I get this error:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'octopus-deploy'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Source\GitRepos\angular-tid\gulpfile.js:11:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

It appears that the `main` property of the `package.json` is wrong. It's set to `"./lib/client.js"`. When I change this to `"./lib/octopus-deploy.js"` it begins to work fine.

Along the same vein the documentation on npmjs says the command to install is:

```
npm install node-octopus-deploy
```

This doesn't work. I need to do this instead

```
npm install octopus-deploy
```

Perhaps the package name has changed recently and the documentation not updated.

**Comment by iojohnso** [comment]
Thanks for the feedback.  I'm no longer using this library, therefore have no interest in maintaining it.

Are you interested in taking ownership of this library?

**Comment by dgurram** [comment]
Submitted a pull request for the fix, along with the other issue that I raised. Hope you're able to merge and update npmjs. Thanks!

**Comment by iojohnso** [comment]
Pushed to NPM.  Can i close this?

**Comment by dgurram** [comment]
Awesome. Yup can see it up there. All good to close.
